name: ams-data-processing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipython
  - ipykernel
  - jupyterlab
  - notebook
  - ipywidgets
  - ipympl
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - statsmodels
  - scikit-posthocs
  - statannotations
  - pingouin
  - yellowbrick
  - umap-learn
  - session-info
  - scikit-bio
  - omicverse
  - pip
  - pip:
    - pyopenms
    - pyopenms-viz
    - matchms
    - matchmsextras
    - networkx
    - peakutils
    - rdkit
    - dockstring
    - fermo-core
    - alphapept
    - tooluniverse
    - google-adk
    - coloredlogs
    - molplotly
    - dash
    - huggingface-hub
    - h5py
    - openpyxl
    - requests
    - tqdm
    - pillow
    - chemprop
    - PyComplexHeatmap